[main]
#font=JetBrains Mono Nerd Font:weight=bold:size=14
dpi-aware=yes
# Using specific character width instead of percentage for a consistent shape
width=70
lines=7
line-height=25
#fields=name,generic,comment,categories,filename,keywords
terminal=foot
#prompt="➜  " 
#icon-theme=Papirus-Dark
layer=overlay

# Spacing to create the "Floating" feel
#horizontal-pad=40
vertical-pad=20
inner-pad=10

[colors]
# Dark background with high transparency (requires compositor blur for best effect)
background=1D1D20f2
text=cdd6f4ff
match=f38ba8ff
selection=151515ff
selection-text=cdd6f4ff
selection-match=f38ba8ff
border=000000ff

[border]
width=1
radius=12
