source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/programs.conf
source = ~/.config/hypr/conf.d/autostart.conf
source = ~/.config/hypr/conf.d/env.conf
source = ~/.config/hypr/conf.d/permissions.conf
source = ~/.config/hypr/conf.d/decoration.conf
source = ~/.config/hypr/conf.d/animation.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/keybinds.conf
source = ~/.config/hypr/conf.d/rules.conf
