#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
exec-once = awww-daemon
  exec-once = bash -c 'sleep 1 && wallpaper-switch "$(cat ~/.config/current-wallpaper 2>/dev/null || echo ${HOME}/wallpapers/default.jpg)
