################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,preferred,auto,auto

#1080p 24inch monitor
monitor = DP-3, 1920x1080@60, 0x0, 1
# Replace 'DP-1' with your actual monitor name from 'hyprctl monitors'
monitor = HDMI-A-1, preferred, auto, 1.5, bitdepth, 10, cm, hdr, sdrbrightness, 1.2, sdrsaturation, 0.98
